// GENERATED by scripts/package-bibles.mjs — sizes and counts come from the
// packaged files themselves, so they cannot drift from what is published.
//
// All ten are in the public domain. NIV, ESV, NLT, NASB, CSB and The Message
// are copyrighted and cannot be bundled; chapters link out to them instead.

export type Translation = {
  id: string;
  name: string;
  year: string;
  books: number;
  verses: number;
  bytes: number;
  note: string;
};

export const TRANSLATIONS: Translation[] = [
  { id: "BSB", name: "Berean Standard Bible", year: "2022", books: 66, verses: 31102, bytes: 1215055,
    note: "Modern English. The most readable of the free translations." },
  { id: "NHEB", name: "New Heart English Bible", year: "2010", books: 66, verses: 31104, bytes: 1200558,
    note: "Modern English, in the King James tradition." },
  { id: "KJV", name: "King James Version", year: "1769", books: 66, verses: 31102, bytes: 1213587,
    note: "The classic. Formal, familiar, four centuries old." },
  { id: "AKJV", name: "American King James", year: "1999", books: 66, verses: 31102, bytes: 1200161,
    note: "The King James wording with archaic words updated." },
  { id: "ASV", name: "American Standard Version", year: "1901", books: 66, verses: 31102, bytes: 1211484,
    note: "Precise and literal. The basis of many later translations." },
  { id: "YLT", name: "Young's Literal Translation", year: "1898", books: 66, verses: 31102, bytes: 1206227,
    note: "Word-for-word from the original. Useful for study, hard to read aloud." },
  { id: "Darby", name: "Darby Bible", year: "1890", books: 66, verses: 31102, bytes: 1219835,
    note: "A literal translation with careful attention to tense." },
  { id: "BBE", name: "Bible in Basic English", year: "1965", books: 66, verses: 31102, bytes: 1175209,
    note: "A deliberately small vocabulary. The plainest English here." },
  { id: "CPDV", name: "Catholic Public Domain", year: "2009", books: 78, verses: 37255, bytes: 1486518,
    note: "Includes the twelve deuterocanonical books." },
  { id: "Webster", name: "Webster's Bible", year: "1833", books: 66, verses: 31102, bytes: 1236198,
    note: "Noah Webster's revision of the King James." },
];

// Where the packaged translations are served from. Override it to re-host the
// data somewhere else without touching the app.
const RELEASE =
  process.env.EXPO_PUBLIC_BIBLE_BASE ??
  "https://github.com/yhrnhj2k49-svg/lamp-unto-my-feet/releases/download/bible-data-v1";

export const assetUrl = (id: string) => `${RELEASE}/${id}.json.gz`;

export const byId = (id: string) => TRANSLATIONS.find((t) => t.id === id);

export const megabytes = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`;

/** Copyrighted translations we can link to but never reproduce. */
export const OFFSITE = [
  { label: "NIV", search: "NIV" },
  { label: "ESV", search: "ESV" },
  { label: "NLT", search: "NLT" },
];

export const offsiteUrl = (ref: string, version: string) =>
  `https://www.biblegateway.com/passage/?search=${encodeURIComponent(ref)}&version=${version}`;
