// GENERATED by scripts/build-corpus.ts — do not edit by hand.
// 167 passages, King James Version (public domain), each with its
// setting. Readings quote the text verbatim from here, and /living looks
// passages up here rather than trusting text sent by a caller.

export type CorpusPassage = { ref: string; text: string; setting: string };

export const PASSAGES: CorpusPassage[] = [
  {
    "ref": "Philippians 4:6-7",
    "text": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
    "setting": "Paul, writing from prison, to the church at Philippi, a community he loved and who had stood by him."
  },
  {
    "ref": "1 Peter 5:7",
    "text": "Casting all your care upon him; for he careth for you.",
    "setting": "A letter bearing Peter's name, to scattered Christians in Asia Minor who were facing hostility for their faith."
  },
  {
    "ref": "Matthew 6:34",
    "text": "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof.",
    "setting": "Jesus, in the Sermon on the Mount, to crowds of ordinary people in Galilee living close to the edge."
  },
  {
    "ref": "Matthew 6:26",
    "text": "Behold the fowls of the air: for they sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?",
    "setting": "Jesus, in the Sermon on the Mount, pointing his listeners to the birds overhead as they sat on a Galilean hillside."
  },
  {
    "ref": "Isaiah 26:3",
    "text": "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
    "setting": "From a song Isaiah gives to Judah, looking ahead to a day when God's people would live securely."
  },
  {
    "ref": "Psalm 94:19",
    "text": "In the multitude of my thoughts within me thy comforts delight my soul.",
    "setting": "An unnamed psalmist, crying out against injustice and the arrogance of people who harm the vulnerable."
  },
  {
    "ref": "John 14:27",
    "text": "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
    "setting": "Jesus to his disciples at the Last Supper, hours before his arrest, preparing them to lose him."
  },
  {
    "ref": "Psalm 55:22",
    "text": "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.",
    "setting": "A psalm attributed to David, written in the pain of being betrayed by a close companion."
  },
  {
    "ref": "Isaiah 41:10",
    "text": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
    "setting": "God speaking to Israel in exile in Babylon, a people defeated, scattered and afraid they had been abandoned."
  },
  {
    "ref": "Psalm 27:1",
    "text": "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
    "setting": "A psalm attributed to David, a man who lived for years with real enemies and real danger."
  },
  {
    "ref": "Psalm 56:3",
    "text": "What time I am afraid, I will trust in thee.",
    "setting": "Attributed to David, from when the Philistines seized him in Gath, alone and in danger."
  },
  {
    "ref": "2 Timothy 1:7",
    "text": "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
    "setting": "A letter from Paul, in prison near the end of his life, to Timothy, his young and sometimes timid protégé."
  },
  {
    "ref": "Joshua 1:9",
    "text": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
    "setting": "God to Joshua, newly in charge after Moses died, about to lead a whole people across the Jordan."
  },
  {
    "ref": "Psalm 23:4",
    "text": "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
    "setting": "A psalm attributed to David, who knew the work of a shepherd guiding sheep through dangerous ground."
  },
  {
    "ref": "Psalm 34:18",
    "text": "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.",
    "setting": "Attributed to David, written after he escaped danger by pretending to be mad before a foreign king."
  },
  {
    "ref": "John 11:35",
    "text": "Jesus wept.",
    "setting": "At the tomb of Lazarus in Bethany, with his sisters Mary and Martha grieving, just before Jesus raised him."
  },
  {
    "ref": "Matthew 5:4",
    "text": "Blessed are they that mourn: for they shall be comforted.",
    "setting": "Jesus, opening the Sermon on the Mount with blessings on the people who least looked blessed."
  },
  {
    "ref": "Psalm 147:3",
    "text": "He healeth the broken in heart, and bindeth up their wounds.",
    "setting": "A hymn celebrating God rebuilding Jerusalem and gathering the exiles home after the Babylonian captivity."
  },
  {
    "ref": "Psalm 30:5",
    "text": "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.",
    "setting": "Attributed to David, a song of thanks after being brought back from a time he thought would destroy him."
  },
  {
    "ref": "2 Corinthians 1:3-4",
    "text": "Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort; Who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble, by the comfort wherewith we ourselves are comforted of God.",
    "setting": "Paul to the church at Corinth, after a crisis in Asia so severe he says he despaired even of life."
  },
  {
    "ref": "Revelation 21:4",
    "text": "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.",
    "setting": "John's vision on the island of Patmos, written to small churches under pressure from the Roman empire."
  },
  {
    "ref": "Ecclesiastes 3:4",
    "text": "A time to weep, and a time to laugh; a time to mourn, and a time to dance.",
    "setting": "From the Teacher of Ecclesiastes, reflecting honestly on how life moves in seasons no one fully controls."
  },
  {
    "ref": "Psalm 42:11",
    "text": "Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God: for I shall yet praise him, who is the health of my countenance, and my God.",
    "setting": "By the sons of Korah, from a psalmist far from the temple and taunted by people asking where their God is."
  },
  {
    "ref": "Lamentations 3:22-23",
    "text": "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.",
    "setting": "Written in the ruins of Jerusalem after the Babylonians burned it in 587 BC; traditionally attributed to Jeremiah."
  },
  {
    "ref": "Psalm 40:1-2",
    "text": "I waited patiently for the LORD; and he inclined unto me, and heard my cry. He brought me up also out of an horrible pit, out of the miry clay, and set my feet upon a rock, and established my goings.",
    "setting": "A psalm attributed to David, looking back on being rescued after a long and patient wait."
  },
  {
    "ref": "1 Kings 19:5-7",
    "text": "And as he lay and slept under a juniper tree, behold, then an angel touched him, and said unto him, Arise and eat. And he looked, and, behold, there was a cake baken on the coals, and a cruse of water at his head... And the angel of the LORD came again the second time, and touched him, and said, Arise and eat; because the journey is too great for thee.",
    "setting": "Elijah, exhausted and asking God to let him die, fleeing Queen Jezebel right after his victory on Mount Carmel."
  },
  {
    "ref": "Psalm 88:18",
    "text": "Lover and friend hast thou put far from me, and mine acquaintance into darkness.",
    "setting": "By Heman the Ezrahite, the bleakest of the psalms, which ends in darkness with no turn toward hope."
  },
  {
    "ref": "Isaiah 61:3",
    "text": "To appoint unto them that mourn in Zion, to give unto them beauty for ashes, the oil of joy for mourning, the garment of praise for the spirit of heaviness.",
    "setting": "To exiles back in a ruined Jerusalem; centuries later Jesus read this passage aloud in the synagogue at Nazareth."
  },
  {
    "ref": "Hebrews 13:5",
    "text": "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee.",
    "setting": "An anonymous letter to Jewish Christians under pressure, quoting the promise first given to Joshua."
  },
  {
    "ref": "Psalm 139:7-10",
    "text": "Whither shall I go from thy spirit? or whither shall I flee from thy presence?... If I take the wings of the morning, and dwell in the uttermost parts of the sea; Even there shall thy hand lead me, and thy right hand shall hold me.",
    "setting": "A psalm attributed to David, marveling that there is nowhere he could go that God would not already be."
  },
  {
    "ref": "Psalm 68:6",
    "text": "God setteth the solitary in families.",
    "setting": "Attributed to David, a processional song celebrating God as the defender of orphans and widows."
  },
  {
    "ref": "Psalm 25:16",
    "text": "Turn thee unto me, and have mercy upon me; for I am desolate and afflicted.",
    "setting": "A psalm attributed to David, written as an alphabet acrostic prayer from a lonely and troubled heart."
  },
  {
    "ref": "Matthew 28:20",
    "text": "Lo, I am with you alway, even unto the end of the world.",
    "setting": "The last words of Matthew's gospel, spoken by the risen Jesus on a mountain in Galilee."
  },
  {
    "ref": "Ephesians 4:26",
    "text": "Be ye angry, and sin not: let not the sun go down upon your wrath.",
    "setting": "A letter from Paul to the church at Ephesus, teaching a mixed community how to live together honestly."
  },
  {
    "ref": "James 1:19-20",
    "text": "Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath: For the wrath of man worketh not the righteousness of God.",
    "setting": "Traditionally James, the brother of Jesus and leader of the Jerusalem church, writing to scattered believers."
  },
  {
    "ref": "Proverbs 15:1",
    "text": "A soft answer turneth away wrath: but grievous words stir up anger.",
    "setting": "From the collected proverbs of Solomon, practical wisdom for ordinary life in ancient Israel."
  },
  {
    "ref": "Romans 12:19",
    "text": "Dearly beloved, avenge not yourselves, but rather give place unto wrath: for it is written, Vengeance is mine; I will repay, saith the Lord.",
    "setting": "Paul to the church in Rome, a divided community of Jewish and Gentile believers he had not yet visited."
  },
  {
    "ref": "Psalm 4:4",
    "text": "Stand in awe, and sin not: commune with your own heart upon your bed, and be still.",
    "setting": "A psalm attributed to David, an evening prayer from someone surrounded by people speaking against him."
  },
  {
    "ref": "1 John 1:9",
    "text": "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.",
    "setting": "A letter traditionally attributed to the apostle John, to churches unsettled by division and false teaching."
  },
  {
    "ref": "Psalm 103:12",
    "text": "As far as the east is from the west, so far hath he removed our transgressions from us.",
    "setting": "A psalm attributed to David, praising God for a forgiveness that outlasts every failure."
  },
  {
    "ref": "Romans 8:1",
    "text": "There is therefore now no condemnation to them which are in Christ Jesus.",
    "setting": "Paul to the church in Rome, just after describing his own struggle to do the good he wants."
  },
  {
    "ref": "Isaiah 1:18",
    "text": "Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.",
    "setting": "Isaiah to Judah in the eighth century BC, confronting a people whose worship had gone empty and cruel."
  },
  {
    "ref": "Psalm 51:10",
    "text": "Create in me a clean heart, O God; and renew a right spirit within me.",
    "setting": "Attributed to David after the prophet Nathan confronted him over Bathsheba and the killing of her husband Uriah."
  },
  {
    "ref": "Joel 2:25",
    "text": "And I will restore to you the years that the locust hath eaten.",
    "setting": "The prophet Joel, writing after a locust plague stripped the land bare and ruined years of harvest."
  },
  {
    "ref": "Micah 7:19",
    "text": "He will turn again, he will have compassion upon us; he will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea.",
    "setting": "The prophet Micah, in the eighth century BC, closing a book of hard warnings with a song of mercy."
  },
  {
    "ref": "Colossians 3:13",
    "text": "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.",
    "setting": "Paul to the church at Colossae, describing how people who have been forgiven live together."
  },
  {
    "ref": "Matthew 18:21-22",
    "text": "Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? till seven times? Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven.",
    "setting": "Jesus answering Peter, who thought forgiving seven times was already generous, before telling a parable about debt."
  },
  {
    "ref": "Ephesians 4:32",
    "text": "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
    "setting": "A letter from Paul to the church at Ephesus, on how people shaped by grace speak to and treat each other."
  },
  {
    "ref": "Luke 23:34",
    "text": "Then said Jesus, Father, forgive them; for they know not what they do.",
    "setting": "Jesus on the cross at Golgotha, praying for the soldiers who had just nailed him there."
  },
  {
    "ref": "1 Corinthians 10:13",
    "text": "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it.",
    "setting": "Paul to the church at Corinth, a port city famous for its temptations, warning against overconfidence."
  },
  {
    "ref": "Romans 7:15",
    "text": "For that which I do I allow not: for what I would, that do I not; but what I hate, that do I.",
    "setting": "Paul to the church in Rome, describing the war inside a person who wants to do right and keeps failing."
  },
  {
    "ref": "Hebrews 4:15-16",
    "text": "For we have not an high priest which cannot be touched with the feeling of our infirmities; but was in all points tempted like as we are, yet without sin. Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.",
    "setting": "An anonymous letter to Jewish Christians tempted to give up their faith under pressure."
  },
  {
    "ref": "James 4:7",
    "text": "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
    "setting": "Traditionally James, the brother of Jesus, to believers torn by quarrels and competing desires."
  },
  {
    "ref": "Proverbs 24:16",
    "text": "For a just man falleth seven times, and riseth up again: but the wicked shall fall into mischief.",
    "setting": "From the sayings of the wise in Proverbs, on how the righteous live through trouble."
  },
  {
    "ref": "Galatians 5:1",
    "text": "Stand fast therefore in the liberty wherewith Christ hath made us free, and be not entangled again with the yoke of bondage.",
    "setting": "Paul to the churches in Galatia, who were being pressured back into rules they had been freed from."
  },
  {
    "ref": "Mark 9:24",
    "text": "And straightway the father of the child cried out, and said with tears, Lord, I believe; help thou mine unbelief.",
    "setting": "A desperate father whose son had seizures, speaking to Jesus after the disciples had failed to heal the boy."
  },
  {
    "ref": "Proverbs 3:5-6",
    "text": "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
    "setting": "A father's teaching to his son in the opening chapters of Proverbs, on where to rest your weight."
  },
  {
    "ref": "Isaiah 55:8-9",
    "text": "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD. For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.",
    "setting": "God's invitation to exiles in Babylon to come home, offered freely, like water to the thirsty."
  },
  {
    "ref": "Habakkuk 1:2",
    "text": "O LORD, how long shall I cry, and thou wilt not hear! even cry out unto thee of violence, and thou wilt not save!",
    "setting": "The prophet Habakkuk, late in the seventh century BC, arguing with God as violence spread and Babylon rose."
  },
  {
    "ref": "Hebrews 11:1",
    "text": "Now faith is the substance of things hoped for, the evidence of things not seen.",
    "setting": "An anonymous letter, opening a long list of people who kept faith without seeing the promise fulfilled."
  },
  {
    "ref": "Isaiah 40:31",
    "text": "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
    "setting": "Comfort spoken to exiles in Babylon who had concluded that God had forgotten them."
  },
  {
    "ref": "Psalm 27:14",
    "text": "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.",
    "setting": "A psalm attributed to David, ending a prayer written in the middle of danger and false accusation."
  },
  {
    "ref": "Habakkuk 2:3",
    "text": "For the vision is yet for an appointed time, but at the end it shall speak, and not lie: though it tarry, wait for it; because it will surely come, it will not tarry.",
    "setting": "God's answer to the prophet Habakkuk, who had demanded to know why injustice was being allowed."
  },
  {
    "ref": "Ecclesiastes 3:1",
    "text": "To every thing there is a season, and a time to every purpose under the heaven.",
    "setting": "From the Teacher of Ecclesiastes, reflecting on how every part of life comes in its own time."
  },
  {
    "ref": "Galatians 6:9",
    "text": "And let us not be weary in well doing: for in due season we shall reap, if we faint not.",
    "setting": "Paul closing his letter to the Galatian churches, urging them not to quit doing good."
  },
  {
    "ref": "Psalm 130:5-6",
    "text": "I wait for the LORD, my soul doth wait, and in his word do I hope. My soul waiteth for the Lord more than they that watch for the morning: I say, more than they that watch for the morning.",
    "setting": "A song of ascents, sung by pilgrims on the road up to Jerusalem, from someone in deep trouble."
  },
  {
    "ref": "Philippians 4:19",
    "text": "But my God shall supply all your need according to his riches in glory by Christ Jesus.",
    "setting": "Paul, in prison, thanking the Philippians for a gift they sent him out of their own poverty."
  },
  {
    "ref": "Matthew 6:31-33",
    "text": "Therefore take no thought, saying, What shall we eat? or, What shall we drink? or, Wherewithal shall we be clothed?... But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
    "setting": "Jesus in the Sermon on the Mount, speaking to poor Galilean farmers and fishermen about food and clothing."
  },
  {
    "ref": "Psalm 37:25",
    "text": "I have been young, and now am old; yet have I not seen the righteous forsaken, nor his seed begging bread.",
    "setting": "A psalm attributed to David, written as the wisdom of an old man looking back on a long life."
  },
  {
    "ref": "1 Timothy 6:6-8",
    "text": "But godliness with contentment is great gain. For we brought nothing into this world, and it is certain we can carry nothing out. And having food and raiment let us be therewith content.",
    "setting": "A letter from Paul to Timothy in Ephesus, warning about people who treated faith as a way to get rich."
  },
  {
    "ref": "Luke 12:15",
    "text": "And he said unto them, Take heed, and beware of covetousness: for a man's life consisteth not in the abundance of the things which he possesseth.",
    "setting": "Jesus, after a man in the crowd asked him to make his brother share the family inheritance."
  },
  {
    "ref": "Colossians 3:23",
    "text": "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
    "setting": "Paul to the church at Colossae, addressed to enslaved people doing work they had not chosen."
  },
  {
    "ref": "Jeremiah 29:11",
    "text": "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.",
    "setting": "Jeremiah's letter to the exiles in Babylon, telling them to build houses and settle in for seventy years."
  },
  {
    "ref": "Ephesians 2:10",
    "text": "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.",
    "setting": "A letter from Paul to the church at Ephesus, right after saying that salvation is a gift and not earned."
  },
  {
    "ref": "Romans 8:28",
    "text": "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
    "setting": "Paul to the church in Rome, in a chapter about suffering, groaning and hope."
  },
  {
    "ref": "Proverbs 16:3",
    "text": "Commit thy works unto the LORD, and thy thoughts shall be established.",
    "setting": "From the proverbs of Solomon, practical wisdom about planning and God's part in it."
  },
  {
    "ref": "Ecclesiastes 9:10",
    "text": "Whatsoever thy hand findeth to do, do it with thy might.",
    "setting": "From the Teacher of Ecclesiastes, writing with death in view about making the most of life."
  },
  {
    "ref": "Psalm 119:105",
    "text": "Thy word is a lamp unto my feet, and a light unto my path.",
    "setting": "From the longest psalm, an anonymous alphabet acrostic in praise of God's word."
  },
  {
    "ref": "James 1:5",
    "text": "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
    "setting": "Traditionally James, the brother of Jesus, writing to believers facing trials and hard decisions."
  },
  {
    "ref": "Isaiah 30:21",
    "text": "And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it, when ye turn to the right hand, and when ye turn to the left.",
    "setting": "Isaiah to Judah, who were trusting an alliance with Egypt instead of turning back to God."
  },
  {
    "ref": "Proverbs 16:9",
    "text": "A man's heart deviseth his way: but the LORD directeth his steps.",
    "setting": "From the proverbs of Solomon, on the gap between our plans and what actually happens."
  },
  {
    "ref": "Psalm 32:8",
    "text": "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.",
    "setting": "A psalm attributed to David, written after the relief of finally confessing what he had hidden."
  },
  {
    "ref": "Proverbs 11:14",
    "text": "Where no counsel is, the people fall: but in the multitude of counsellors there is safety.",
    "setting": "From the proverbs of Solomon, on how decisions go better with many advisers."
  },
  {
    "ref": "2 Corinthians 12:9",
    "text": "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.",
    "setting": "Paul to Corinth, describing a thorn in the flesh he had begged God three times to remove."
  },
  {
    "ref": "Psalm 73:26",
    "text": "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.",
    "setting": "Asaph, a temple musician, after nearly losing his faith watching the wicked prosper."
  },
  {
    "ref": "Romans 8:18",
    "text": "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.",
    "setting": "Paul to the church in Rome, writing as someone who had been beaten, imprisoned and shipwrecked."
  },
  {
    "ref": "2 Corinthians 4:16-17",
    "text": "For which cause we faint not; but though our outward man perish, yet the inward man is renewed day by day. For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory.",
    "setting": "Paul to Corinth, writing about a body worn down by years of hardship in his work."
  },
  {
    "ref": "Psalm 41:3",
    "text": "The LORD will strengthen him upon the bed of languishing: thou wilt make all his bed in his sickness.",
    "setting": "A psalm attributed to David, written from a sickbed while enemies waited for him to die."
  },
  {
    "ref": "Micah 6:8",
    "text": "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?",
    "setting": "Micah to Judah in the eighth century BC, answering people who thought more sacrifices would please God."
  },
  {
    "ref": "Amos 5:24",
    "text": "But let judgment run down as waters, and righteousness as a mighty stream.",
    "setting": "Amos, a shepherd from Tekoa, to wealthy Israel holding religious festivals while crushing the poor."
  },
  {
    "ref": "Psalm 9:9",
    "text": "The LORD also will be a refuge for the oppressed, a refuge in times of trouble.",
    "setting": "A psalm attributed to David, praising God as the one who does not forget the afflicted."
  },
  {
    "ref": "Proverbs 31:8-9",
    "text": "Open thy mouth for the dumb in the cause of all such as are appointed to destruction. Open thy mouth, judge righteously, and plead the cause of the poor and needy.",
    "setting": "The words of King Lemuel, which the text says his mother taught him about using power rightly."
  },
  {
    "ref": "Psalm 37:1-2",
    "text": "Fret not thyself because of evildoers, neither be thou envious against the workers of iniquity. For they shall soon be cut down like the grass, and wither as the green herb.",
    "setting": "A psalm attributed to David, an alphabet acrostic of wisdom about not envying people who do wrong."
  },
  {
    "ref": "Psalm 55:12-14",
    "text": "For it was not an enemy that reproached me; then I could have borne it... But it was thou, a man mine equal, my guide, and mine acquaintance. We took sweet counsel together, and walked unto the house of God in company.",
    "setting": "A psalm attributed to David, written after being betrayed by a close friend he once worshipped beside."
  },
  {
    "ref": "Genesis 50:20",
    "text": "But as for you, ye thought evil against me; but God meant it unto good, to bring to pass, as it is this day, to save much people alive.",
    "setting": "Joseph to the brothers who sold him into slavery, after their father died in Egypt and they feared his revenge."
  },
  {
    "ref": "Psalm 41:9",
    "text": "Yea, mine own familiar friend, in whom I trusted, which did eat of my bread, hath lifted up his heel against me.",
    "setting": "A psalm attributed to David, which Jesus later quoted about Judas at the Last Supper."
  },
  {
    "ref": "1 Corinthians 13:4-7",
    "text": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things.",
    "setting": "Paul to a divided, competitive church in Corinth, arguing over who was most spiritual."
  },
  {
    "ref": "Ecclesiastes 4:9-10",
    "text": "Two are better than one; because they have a good reward for their labour. For if they fall, the one will lift up his fellow: but woe to him that is alone when he falleth: for he hath not another to help him up.",
    "setting": "From the Teacher of Ecclesiastes, reflecting on the loneliness of people who work only for themselves."
  },
  {
    "ref": "Proverbs 27:17",
    "text": "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.",
    "setting": "From the proverbs of Solomon that King Hezekiah's scribes copied out centuries later."
  },
  {
    "ref": "1 Peter 4:8",
    "text": "And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.",
    "setting": "A letter bearing Peter's name, to Christians facing suffering and learning to hold together under strain."
  },
  {
    "ref": "Ephesians 4:2-3",
    "text": "With all lowliness and meekness, with longsuffering, forbearing one another in love; Endeavouring to keep the unity of the Spirit in the bond of peace.",
    "setting": "A letter from Paul to the church at Ephesus, urging a mixed community to keep the peace they had been given."
  },
  {
    "ref": "Luke 15:20",
    "text": "And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him.",
    "setting": "The parable of the prodigal son, told by Jesus to religious leaders grumbling that he welcomed sinners."
  },
  {
    "ref": "Proverbs 22:6",
    "text": "Train up a child in the way he should go: and when he is old, he will not depart from it.",
    "setting": "From the proverbs of Solomon, practical wisdom on raising children over a lifetime."
  },
  {
    "ref": "Ephesians 6:4",
    "text": "And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord.",
    "setting": "A letter from Paul to the church at Ephesus, in household instructions for a culture where fathers held near-absolute authority."
  },
  {
    "ref": "Deuteronomy 6:6-7",
    "text": "And these words, which I command thee this day, shall be in thine heart: And thou shalt teach them diligently unto thy children, and shalt talk of them when thou sittest in thine house, and when thou walkest by the way, and when thou liest down, and when thou risest up.",
    "setting": "Moses to Israel on the edge of the promised land, straight after the Shema, the central confession of faith."
  },
  {
    "ref": "1 Thessalonians 5:16-18",
    "text": "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
    "setting": "Paul to a young church in Thessalonica, in what is probably his earliest surviving letter."
  },
  {
    "ref": "Psalm 103:2",
    "text": "Bless the LORD, O my soul, and forget not all his benefits.",
    "setting": "A psalm attributed to David, calling his own soul to remember every good thing God had done."
  },
  {
    "ref": "James 1:17",
    "text": "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.",
    "setting": "Traditionally James, the brother of Jesus, writing to believers who were blaming God for their temptations."
  },
  {
    "ref": "Nehemiah 8:10",
    "text": "Neither be ye sorry; for the joy of the LORD is your strength.",
    "setting": "Nehemiah and Ezra to returned exiles who wept as they heard God's law read aloud."
  },
  {
    "ref": "Psalm 118:24",
    "text": "This is the day which the LORD hath made; we will rejoice and be glad in it.",
    "setting": "A festival hymn, the last of the Hallel psalms sung at Passover, which Jesus likely sang the night of his arrest."
  },
  {
    "ref": "Proverbs 16:18",
    "text": "Pride goeth before destruction, and an haughty spirit before a fall.",
    "setting": "From the proverbs of Solomon, a warning handed down about the fall that follows arrogance."
  },
  {
    "ref": "Galatians 6:4",
    "text": "But let every man prove his own work, and then shall he have rejoicing in himself alone, and not in another.",
    "setting": "Paul to the churches in Galatia, warning believers against measuring themselves against one another."
  },
  {
    "ref": "Psalm 73:2-3",
    "text": "But as for me, my feet were almost gone; my steps had well nigh slipped. For I was envious at the foolish, when I saw the prosperity of the wicked.",
    "setting": "Asaph, a temple musician, confessing how close envy brought him to losing his faith."
  },
  {
    "ref": "James 4:10",
    "text": "Humble yourselves in the sight of the Lord, and he shall lift you up.",
    "setting": "Traditionally James, the brother of Jesus, writing to believers striving and quarrelling for position."
  },
  {
    "ref": "Proverbs 14:30",
    "text": "A sound heart is the life of the flesh: but envy the rottenness of the bones.",
    "setting": "From the proverbs of Solomon, on how envy corrodes a person from the inside."
  },
  {
    "ref": "Matthew 11:28-30",
    "text": "Come unto me, all ye that labour and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light.",
    "setting": "Jesus speaking to ordinary people weighed down by religious demands they could never meet."
  },
  {
    "ref": "Psalm 23:1-3",
    "text": "The LORD is my shepherd; I shall not want. He maketh me to lie down in green pastures: he leadeth me beside the still waters. He restoreth my soul.",
    "setting": "A psalm attributed to David, who knew from experience how a good shepherd leads sheep to rest."
  },
  {
    "ref": "Exodus 33:14",
    "text": "And he said, My presence shall go with thee, and I will give thee rest.",
    "setting": "God to Moses after the golden calf, when Moses refused to lead the people on without God's presence."
  },
  {
    "ref": "Mark 6:31",
    "text": "And he said unto them, Come ye yourselves apart into a desert place, and rest a while: for there were many coming and going, and they had no leisure so much as to eat.",
    "setting": "Jesus to his disciples returning worn out from their first mission, so busy they had not eaten."
  },
  {
    "ref": "Psalm 127:2",
    "text": "It is vain for you to rise up early, to sit up late, to eat the bread of sorrows: for so he giveth his beloved sleep.",
    "setting": "A song of ascents attributed to Solomon, on the futility of work done without trusting God."
  },
  {
    "ref": "Isaiah 40:29",
    "text": "He giveth power to the faint; and to them that have no might he increaseth strength.",
    "setting": "Comfort spoken to exiles in Babylon who felt too faint to go on."
  },
  {
    "ref": "Isaiah 43:18-19",
    "text": "Remember ye not the former things, neither consider the things of old. Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert.",
    "setting": "God to the exiles in Babylon, promising a new exodus home through the desert."
  },
  {
    "ref": "2 Corinthians 5:17",
    "text": "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
    "setting": "Paul to the church at Corinth, a man who had once persecuted the very people he now led."
  },
  {
    "ref": "Philippians 3:13-14",
    "text": "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before, I press toward the mark for the prize of the high calling of God in Christ Jesus.",
    "setting": "Paul, writing from prison, a man with a violent past and every reason to be haunted by it."
  },
  {
    "ref": "Genesis 12:1",
    "text": "Now the LORD had said unto Abram, Get thee out of thy country, and from thy kindred, and from thy father's house, unto a land that I will shew thee.",
    "setting": "God's call to Abram in Haran, to leave everything familiar for a land not yet named."
  },
  {
    "ref": "John 14:1-3",
    "text": "Let not your heart be troubled: ye believe in God, believe also in me. In my Father's house are many mansions: if it were not so, I would have told you. I go to prepare a place for you.",
    "setting": "Jesus to his disciples at the Last Supper, as they began to realise he was about to leave them."
  },
  {
    "ref": "John 11:25-26",
    "text": "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live: And whosoever liveth and believeth in me shall never die.",
    "setting": "Jesus to Martha, four days after her brother Lazarus was buried, when she told him he had come too late."
  },
  {
    "ref": "Romans 8:38-39",
    "text": "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.",
    "setting": "Paul to the church in Rome, ending a long passage on suffering with a list of everything that cannot win."
  },
  {
    "ref": "1 Corinthians 15:55",
    "text": "O death, where is thy sting? O grave, where is thy victory?",
    "setting": "Paul to the church at Corinth, where some were denying that the dead would be raised."
  },
  {
    "ref": "Job 1:21",
    "text": "Naked came I out of my mother's womb, and naked shall I return thither: the LORD gave, and the LORD hath taken away; blessed be the name of the LORD.",
    "setting": "Job, on the day messengers arrived one after another to tell him everything and everyone was gone."
  },
  {
    "ref": "Matthew 5:44",
    "text": "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you.",
    "setting": "Jesus in the Sermon on the Mount, speaking to people living under Roman occupation."
  },
  {
    "ref": "Romans 12:18",
    "text": "If it be possible, as much as lieth in you, live peaceably with all men.",
    "setting": "Paul to the church in Rome, on living alongside people who did not share their faith."
  },
  {
    "ref": "Exodus 14:14",
    "text": "The LORD shall fight for you, and ye shall hold your peace.",
    "setting": "Moses to the Israelites, trapped and panicking between Pharaoh's army and the Red Sea."
  },
  {
    "ref": "Proverbs 25:21-22",
    "text": "If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink: For thou shalt heap coals of fire upon his head, and the LORD shall reward thee.",
    "setting": "From the proverbs of Solomon copied by Hezekiah's scribes; Paul later quoted it in his letter to Rome."
  },
  {
    "ref": "Micah 7:8",
    "text": "Rejoice not against me, O mine enemy: when I fall, I shall arise; when I sit in darkness, the LORD shall be a light unto me.",
    "setting": "The prophet Micah, speaking for a fallen Jerusalem as its enemies gloated over the ruins."
  },
  {
    "ref": "Psalm 37:23-24",
    "text": "The steps of a good man are ordered by the LORD: and he delighteth in his way. Though he fall, he shall not be utterly cast down: for the LORD upholdeth him with his hand.",
    "setting": "A psalm attributed to David, written as an old man's wisdom about how the righteous are upheld."
  },
  {
    "ref": "John 21:17",
    "text": "He saith unto him the third time, Simon, son of Jonas, lovest thou me? Peter was grieved because he said unto him the third time, Lovest thou me? And he said unto him, Lord, thou knowest all things; thou knowest that I love thee. Jesus saith unto him, Feed my sheep.",
    "setting": "The risen Jesus to Peter by the Sea of Galilee, after Peter had denied knowing him three times."
  },
  {
    "ref": "Psalm 139:13-14",
    "text": "For thou hast possessed my reins: thou hast covered me in my mother's womb. I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.",
    "setting": "A psalm attributed to David, marveling at being known and formed by God before birth."
  },
  {
    "ref": "Isaiah 43:1",
    "text": "But now thus saith the LORD that created thee, O Jacob, and he that formed thee, O Israel, Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine.",
    "setting": "God to Israel in exile in Babylon, a people who had lost their land, their temple and their standing."
  },
  {
    "ref": "Zephaniah 3:17",
    "text": "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.",
    "setting": "The prophet Zephaniah, in the seventh century BC, ending a book of judgment with a love song."
  },
  {
    "ref": "Luke 12:7",
    "text": "But even the very hairs of your head are all numbered. Fear not therefore: ye are of more value than many sparrows.",
    "setting": "Jesus to his disciples, warning of persecution while reminding them how closely God knows them."
  },
  {
    "ref": "1 Samuel 16:7",
    "text": "But the LORD said unto Samuel, Look not on his countenance, or on the height of his stature; because I have refused him: for the LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart.",
    "setting": "God to the prophet Samuel, choosing a king among Jesse's sons while the youngest, David, was out with the sheep."
  },
  {
    "ref": "Romans 15:13",
    "text": "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
    "setting": "Paul, closing the teaching of his letter to Rome with a blessing on a divided church."
  },
  {
    "ref": "Romans 5:3-5",
    "text": "And not only so, but we glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope: And hope maketh not ashamed.",
    "setting": "Paul to the church in Rome, explaining how suffering is worked into hope."
  },
  {
    "ref": "Matthew 7:7",
    "text": "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.",
    "setting": "Jesus in the Sermon on the Mount, teaching his disciples about persistent prayer."
  },
  {
    "ref": "Romans 8:26",
    "text": "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered.",
    "setting": "Paul to the church in Rome, admitting that even he did not always know how to pray."
  },
  {
    "ref": "Psalm 62:8",
    "text": "Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us.",
    "setting": "A psalm attributed to David, written while people around him plotted to bring him down."
  },
  {
    "ref": "Psalm 91:1-2",
    "text": "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust.",
    "setting": "An anonymous psalm of protection, long prayed by people facing danger and plague."
  },
  {
    "ref": "Psalm 46:1",
    "text": "God is our refuge and strength, a very present help in trouble.",
    "setting": "A song of the sons of Korah, the psalm Martin Luther drew on for A Mighty Fortress Is Our God."
  },
  {
    "ref": "Proverbs 18:10",
    "text": "The name of the LORD is a strong tower: the righteous runneth into it, and is safe.",
    "setting": "From the proverbs of Solomon, drawing on the image of a city's fortified tower."
  },
  {
    "ref": "Psalm 121:1-2",
    "text": "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth.",
    "setting": "A song of ascents, sung by pilgrims looking up at the hills on the road to Jerusalem."
  },
  {
    "ref": "Hebrews 12:1-2",
    "text": "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us.",
    "setting": "An anonymous letter, straight after a long list of faithful people who endured before them."
  },
  {
    "ref": "James 1:2-4",
    "text": "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.",
    "setting": "Traditionally James, the brother of Jesus, to scattered believers facing many kinds of trials."
  },
  {
    "ref": "Philippians 4:13",
    "text": "I can do all things through Christ which strengtheneth me.",
    "setting": "Paul, from prison, explaining how he had learned to be content with both plenty and hunger."
  },
  {
    "ref": "2 Timothy 4:7",
    "text": "I have fought a good fight, I have finished my course, I have kept the faith.",
    "setting": "A letter from Paul, near the end of his life and expecting execution, to his protégé Timothy."
  },
  {
    "ref": "Proverbs 18:21",
    "text": "Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof.",
    "setting": "From the proverbs of Solomon, on the power words have to build up or destroy."
  },
  {
    "ref": "Ephesians 4:29",
    "text": "Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying, that it may minister grace unto the hearers.",
    "setting": "A letter from Paul to the church at Ephesus, on speech that builds a community rather than tearing it down."
  },
  {
    "ref": "Psalm 19:14",
    "text": "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer.",
    "setting": "A psalm attributed to David, closing a hymn about creation and God's law with a personal prayer."
  },
  {
    "ref": "Acts 20:35",
    "text": "I have shewed you all things, how that so labouring ye ought to support the weak, and to remember the words of the Lord Jesus, how he said, It is more blessed to give than to receive.",
    "setting": "Paul's farewell to the elders of Ephesus at Miletus, quoting a saying of Jesus recorded nowhere else."
  },
  {
    "ref": "2 Corinthians 9:7",
    "text": "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver.",
    "setting": "Paul to Corinth, while organising a collection for poor believers in Jerusalem."
  },
  {
    "ref": "Proverbs 19:17",
    "text": "He that hath pity upon the poor lendeth unto the LORD; and that which he hath given will he pay him again.",
    "setting": "From the proverbs of Solomon, on how kindness to the poor is seen by God."
  },
  {
    "ref": "Proverbs 9:10",
    "text": "The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.",
    "setting": "From Proverbs, where Wisdom is pictured as a woman calling people to her table."
  },
  {
    "ref": "James 3:17",
    "text": "But the wisdom that is from above is first pure, then peaceable, gentle, and easy to be intreated, full of mercy and good fruits, without partiality, and without hypocrisy.",
    "setting": "Traditionally James, the brother of Jesus, contrasting wisdom from above with bitter, selfish ambition."
  },
  {
    "ref": "Ecclesiastes 7:8",
    "text": "Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.",
    "setting": "From the Teacher of Ecclesiastes, on patience and how things often look different at their end."
  },
  {
    "ref": "Psalm 4:8",
    "text": "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.",
    "setting": "A psalm attributed to David, an evening prayer from someone with enemies who still chose to sleep in peace."
  },
  {
    "ref": "Psalm 3:5",
    "text": "I laid me down and slept; I awaked; for the LORD sustained me.",
    "setting": "A psalm attributed to David, written while fleeing his own son Absalom, who had turned the kingdom against him."
  },
  {
    "ref": "Psalm 63:6",
    "text": "When I remember thee upon my bed, and meditate on thee in the night watches.",
    "setting": "A psalm attributed to David, written in the wilderness of Judah."
  }
];
