// Emits the grounding list the reading server sends to Claude, from the same
// corpus the app ships. Run after editing src/data/verses.ts:
//   npx tsx scripts/build-corpus.ts
import { writeFileSync } from "node:fs";
import { VERSES } from "../src/data/verses";
import { LIVING } from "../src/data/living";

const lines = VERSES.map((v) => `${v.ref} | ${v.text} | ${LIVING[v.ref]?.setting ?? ""}`).join("\n");

writeFileSync(
  "server/src/corpus.ts",
  `// GENERATED by scripts/build-corpus.ts — do not edit by hand.
// ${VERSES.length} passages, King James Version (public domain). Sent to Claude
// as a grounding list so quoted scripture is verbatim rather than recalled.

export const CORPUS = ${JSON.stringify(lines)};

export const CORPUS_SIZE = ${VERSES.length};
`
);

console.log(`corpus.ts: ${VERSES.length} passages, ${lines.length} chars`);
