// Emits the concordance the reading server works from, generated from the same
// corpus the app ships. Run after editing src/data/verses.ts or living.ts:
//   npx tsx scripts/build-corpus.ts
import { writeFileSync } from "node:fs";
import { VERSES } from "../src/data/verses";
import { LIVING } from "../src/data/living";

const passages = VERSES.map((v) => ({ ref: v.ref, text: v.text, setting: LIVING[v.ref]?.setting ?? "" }));

writeFileSync(
  "server/src/corpus.ts",
  `// GENERATED by scripts/build-corpus.ts — do not edit by hand.
// ${passages.length} passages, King James Version (public domain), each with its
// setting. Readings quote the text verbatim from here, and /living looks
// passages up here rather than trusting text sent by a caller.

export type CorpusPassage = { ref: string; text: string; setting: string };

export const PASSAGES: CorpusPassage[] = ${JSON.stringify(passages, null, 2)};
`
);

console.log(`corpus.ts: ${passages.length} passages`);
